[general]
import = [
  "~/.config/alacritty/themes/github_dark_default.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 5
decorations = "Buttonless"
decorations_theme_variant = "Dark"
opacity = 1
blur = true
startup_mode = "Windowed"
resize_increments = false
option_as_alt = "Both"

[font]
size = 18
# normal.family = "Terminess Nerd Font Mono"
normal.family = "IosevkaTerm Nerd Font"
normal.style = "Regular"
bold.style = "Regular"
italic.style = "Regular"
bold_italic.style ="Regular"

[colors]
transparent_background_colors = false

[cursor]
style.shape = "Block"
style.blinking = "On"

[terminal]
shell.program = "/bin/zsh"
shell.args = [
  "-l",
  "-c",
  "tmux attach || tmux new -s 0",
]
