[general]
import = [
  "~/.config/alacritty/themes/kanagawa_paper_ink.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
decorations_theme_variant = "Dark"
opacity = 0.98
blur = false
startup_mode = "Windowed"
resize_increments = true
option_as_alt = "Both"

[font]
size = 20
normal.family = "Terminess Nerd Font Mono"
normal.style = "Regular"
bold.style = "Regular"
italic.style = "Regular"
bold_italic.style ="Regular"

[colors]
transparent_background_colors = true

[cursor]
style.shape = "Block"
style.blinking = "On"

[terminal]
shell.program = "/bin/zsh"
shell.args = [
  "-l",
  "-c",
  "tmux attach || tmux new -s 0",
]
